# Generated by Django 5.2.3 on 2025-07-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_length', models.IntegerField(help_text='Урт (мм)')),
                ('size_width', models.IntegerField(help_text='Өргөн (мм)')),
                ('size_height', models.IntegerField(help_text='Өндөр (мм)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_mnt', models.PositiveIntegerField(help_text='Үнэ (₮)')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Image URL', null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='comma-separated', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('both', 'Pickup & Delivery')], default='both', max_length=10)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttype')),
            ],
        ),
    ]
